# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/cgh/code folder/muduo-study"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/cgh/code folder/muduo-study"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cgh/code folder/muduo-study/CMakeFiles" "/home/cgh/code folder/muduo-study//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cgh/code folder/muduo-study/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mymuduo

# Build rule for target.
mymuduo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mymuduo
.PHONY : mymuduo

# fast build rule for target.
mymuduo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/build
.PHONY : mymuduo/fast

Channel.o: Channel.cc.o
.PHONY : Channel.o

# target to build an object file
Channel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Channel.cc.o
.PHONY : Channel.cc.o

Channel.i: Channel.cc.i
.PHONY : Channel.i

# target to preprocess a source file
Channel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Channel.cc.i
.PHONY : Channel.cc.i

Channel.s: Channel.cc.s
.PHONY : Channel.s

# target to generate assembly for a file
Channel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Channel.cc.s
.PHONY : Channel.cc.s

DefaultPoller.o: DefaultPoller.cc.o
.PHONY : DefaultPoller.o

# target to build an object file
DefaultPoller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/DefaultPoller.cc.o
.PHONY : DefaultPoller.cc.o

DefaultPoller.i: DefaultPoller.cc.i
.PHONY : DefaultPoller.i

# target to preprocess a source file
DefaultPoller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/DefaultPoller.cc.i
.PHONY : DefaultPoller.cc.i

DefaultPoller.s: DefaultPoller.cc.s
.PHONY : DefaultPoller.s

# target to generate assembly for a file
DefaultPoller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/DefaultPoller.cc.s
.PHONY : DefaultPoller.cc.s

EventLoop.o: EventLoop.cc.o
.PHONY : EventLoop.o

# target to build an object file
EventLoop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/EventLoop.cc.o
.PHONY : EventLoop.cc.o

EventLoop.i: EventLoop.cc.i
.PHONY : EventLoop.i

# target to preprocess a source file
EventLoop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/EventLoop.cc.i
.PHONY : EventLoop.cc.i

EventLoop.s: EventLoop.cc.s
.PHONY : EventLoop.s

# target to generate assembly for a file
EventLoop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/EventLoop.cc.s
.PHONY : EventLoop.cc.s

Logger.o: Logger.cc.o
.PHONY : Logger.o

# target to build an object file
Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Logger.cc.o
.PHONY : Logger.cc.o

Logger.i: Logger.cc.i
.PHONY : Logger.i

# target to preprocess a source file
Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Logger.cc.i
.PHONY : Logger.cc.i

Logger.s: Logger.cc.s
.PHONY : Logger.s

# target to generate assembly for a file
Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Logger.cc.s
.PHONY : Logger.cc.s

Poller.o: Poller.cc.o
.PHONY : Poller.o

# target to build an object file
Poller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Poller.cc.o
.PHONY : Poller.cc.o

Poller.i: Poller.cc.i
.PHONY : Poller.i

# target to preprocess a source file
Poller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Poller.cc.i
.PHONY : Poller.cc.i

Poller.s: Poller.cc.s
.PHONY : Poller.s

# target to generate assembly for a file
Poller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Poller.cc.s
.PHONY : Poller.cc.s

TcpServer.o: TcpServer.cc.o
.PHONY : TcpServer.o

# target to build an object file
TcpServer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/TcpServer.cc.o
.PHONY : TcpServer.cc.o

TcpServer.i: TcpServer.cc.i
.PHONY : TcpServer.i

# target to preprocess a source file
TcpServer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/TcpServer.cc.i
.PHONY : TcpServer.cc.i

TcpServer.s: TcpServer.cc.s
.PHONY : TcpServer.s

# target to generate assembly for a file
TcpServer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/TcpServer.cc.s
.PHONY : TcpServer.cc.s

Timestamp.o: Timestamp.cc.o
.PHONY : Timestamp.o

# target to build an object file
Timestamp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Timestamp.cc.o
.PHONY : Timestamp.cc.o

Timestamp.i: Timestamp.cc.i
.PHONY : Timestamp.i

# target to preprocess a source file
Timestamp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Timestamp.cc.i
.PHONY : Timestamp.cc.i

Timestamp.s: Timestamp.cc.s
.PHONY : Timestamp.s

# target to generate assembly for a file
Timestamp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/Timestamp.cc.s
.PHONY : Timestamp.cc.s

inetAddress.o: inetAddress.cc.o
.PHONY : inetAddress.o

# target to build an object file
inetAddress.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/inetAddress.cc.o
.PHONY : inetAddress.cc.o

inetAddress.i: inetAddress.cc.i
.PHONY : inetAddress.i

# target to preprocess a source file
inetAddress.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/inetAddress.cc.i
.PHONY : inetAddress.cc.i

inetAddress.s: inetAddress.cc.s
.PHONY : inetAddress.s

# target to generate assembly for a file
inetAddress.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymuduo.dir/build.make CMakeFiles/mymuduo.dir/inetAddress.cc.s
.PHONY : inetAddress.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mymuduo"
	@echo "... Channel.o"
	@echo "... Channel.i"
	@echo "... Channel.s"
	@echo "... DefaultPoller.o"
	@echo "... DefaultPoller.i"
	@echo "... DefaultPoller.s"
	@echo "... EventLoop.o"
	@echo "... EventLoop.i"
	@echo "... EventLoop.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... Poller.o"
	@echo "... Poller.i"
	@echo "... Poller.s"
	@echo "... TcpServer.o"
	@echo "... TcpServer.i"
	@echo "... TcpServer.s"
	@echo "... Timestamp.o"
	@echo "... Timestamp.i"
	@echo "... Timestamp.s"
	@echo "... inetAddress.o"
	@echo "... inetAddress.i"
	@echo "... inetAddress.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

